apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-fun.fullname" . }}
  labels:
    {{- include "app-fun.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}